name: Release to Hex.pm

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish to Hex.pm
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.17"
          otp-version: "26"

      - run: mix deps.get
      - run: mix hex.publish --yes
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
